# MoveIt controller configuration for dual UR robots
# These controllers interface with ros2_control

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - robot1/scaled_joint_trajectory_controller
    - robot2/scaled_joint_trajectory_controller

  robot1/scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - robot1/shoulder_pan_joint
      - robot1/shoulder_lift_joint
      - robot1/elbow_joint
      - robot1/wrist_1_joint
      - robot1/wrist_2_joint
      - robot1/wrist_3_joint

  robot2/scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - robot2/shoulder_pan_joint
      - robot2/shoulder_lift_joint
      - robot2/elbow_joint
      - robot2/wrist_1_joint
      - robot2/wrist_2_joint
      - robot2/wrist_3_joint
