# Cube Perception Configuration

camera:
  index: 4
  show_preview: false

mock:
  # Kociemba solution to return when use_mock_hardware is true
  cube_solution: "R2 U' B2 D' F2 L2 D R2 U2 B2 U' L' D2 B' U F' R' B2 L D' F U2 R' F2 L' U B2 R2 D F2 L2 U' R2 B2 D' L2 B2"
  cube_description: "Mock cube solution for testing"
