# Cube Perception Configuration

camera:
  index: 4
  show_preview: true

mock:
  # Kociemba solution to return when use_mock_hardware is true
  cube_solution: "R U' F2 L D B' R2 U F' D2 L' B R' U2 D F L2 B' R D' U2 F' L B2 D R' U F2 L' D2 B R2 U' F D' L2 B' R U2 D2 F' L' B2 R' U D' F2 L B R2 D2 U' F' L' B' R U2 D F2 L2 B2 R' D' U F L' B R2 D2 U2 F2 L B' R' D U' F' L2 B2 R D2 U F L' B' R2 D' U2 F2 L2 B R D2 U' F L' B2 R' D U2 F' L2 B R2 D' U F2 L B'"
  #cube_solution: "B2 R' U2 F2 L2 D2 B' U F2"
  cube_description: "Mock cube solution for testing"
