# Cube Perception Configuration

camera:
  index: 4
  show_preview: false

mock:
  # Kociemba solution to return when use_mock_hardware is true
  cube_solution: "R U R' U' F' U"
  cube_description: "Mock cube solution for testing"
