# Cube Perception Configuration

camera:
  index: 4
  show_preview: false

mock:
  # Kociemba solution to return when use_mock_hardware is true
  cube_solution: "R2 U' B2 D' F2 L2 D R2 U2 B2 U' L' D2 B' U F' R' B2 L D' F U2 R' F2 L' U B2 R2 D F2 L2 U' R2 B2 D' L2 B2 F U2 R2 D' L' U F2 D2 B' R2 U' F' L2 D B2 U2 R' F D2 L' U2 B2 R U' F2 D' L2 B U2 R2 F' D2 L2 U' B2 R2 D F2 L' U2 B2 D' R2 F2 U L2 D' B2 R' U2 F2 L2 D2 B' U F2 R2 D' L2 B2 U' F' R2 D2 L' U2 B2 R' F2 D L2 U' B2 R2 D2 F' L2 U2 B2 D' R2 F2 U L2 D' B2 R' U2 F2 L2 D2 B' U F2 R2 D' L2 B2 U' F' R2 D2 L' U2 B2 R' F2 D L2 U' B2 R2 D2 F' L2 U2 B2 D' R2 F2 U L2 D' B2 R' U2 F2 L2 D2 B' U F2"
  #cube_solution: "B2 R' U2 F2 L2 D2 B' U F2"
  cube_description: "Mock cube solution for testing"
