# OMPL planning configuration (fallback planner)

planning_plugins:
  - ompl_interface/OMPLPlanner

robot1_ur_manipulator:
  default_planner_config: RRTConnect
  planner_configs:
    - RRTConnect
  longest_valid_segment_fraction: 0.005

robot2_ur_manipulator:
  default_planner_config: RRTConnect
  planner_configs:
    - RRTConnect
  longest_valid_segment_fraction: 0.005

RRTConnect:
  type: geometric::RRTConnect
  range: 0.0

start_state_max_bounds_error: 0.1

request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision

response_adapters:
  - default_planning_response_adapters/AddTimeOptimalParameterization
  - default_planning_response_adapters/ValidateSolution
  - default_planning_response_adapters/DisplayMotionPath
