planning_plugins:
  - ompl_interface/OMPLPlanner

request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision

response_adapters:
  - default_planning_response_adapters/AddTimeOptimalParameterization
  - default_planning_response_adapters/ValidateSolution
  - default_planning_response_adapters/DisplayMotionPath

start_state_max_bounds_error: 0.1

robot1_ur_manipulator:
  default_planner_config: RRTConnect
  planner_configs:
    - RRTConnect
    - RRTstar
    - PRMstar
  projection_evaluator: joints(robot1_shoulder_pan_joint,robot1_shoulder_lift_joint)

robot2_ur_manipulator:
  default_planner_config: RRTConnect
  planner_configs:
    - RRTConnect
    - RRTstar
    - PRMstar
  projection_evaluator: joints(robot2_shoulder_pan_joint,robot2_shoulder_lift_joint)

RRTConnect:
  type: geometric::RRTConnect
  range: 0.0

RRTstar:
  type: geometric::RRTstar
  range: 0.0
  goal_bias: 0.1
  delay_collision_checking: 1

PRMstar:
  type: geometric::PRMstar
