# Pilz industrial motion planner configuration (primary planner)

planning_plugins:
  - pilz_industrial_motion_planner/CommandPlanner

default_planner_config: PTP

start_state_max_bounds_error: 0.1

request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision

response_adapters:
  - default_planning_response_adapters/ValidateSolution
  - default_planning_response_adapters/DisplayMotionPath

capabilities: >-
  pilz_industrial_motion_planner/MoveGroupSequenceAction
  pilz_industrial_motion_planner/MoveGroupSequenceService

cartesian_limits:
  max_trans_vel: 0.2           # Increased from 0.1
  max_trans_acc: 1.0           # Increased from 0.5
  max_trans_dec: -1.0          # Increased from -0.5
  max_rot_vel: 1.5             # Increased from 0.5 - important for wrist rotation
