###############################################
# MoveIt Servo Configuration for Robot 2
###############################################

moveit_servo:
  use_gazebo: false

  ## Properties of incoming commands
  command_in_type: "speed_units"
  scale:
    linear: 0.5
    rotational: 0.5
    joint: 0.5

  system_latency_compensation: 0.04

  ## Properties of outgoing commands
  publish_period: 0.01
  low_latency_mode: false
  command_out_type: trajectory_msgs/JointTrajectory
  publish_joint_positions: true
  publish_joint_velocities: true
  publish_joint_accelerations: false

  ## Smoothing filter
  smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"

  is_primary_planning_scene_monitor: false

  ## Incoming Joint State properties
  low_pass_filter_coeff: 10.0

  ## MoveIt properties - Robot 2
  move_group_name: robot2_ur_manipulator
  planning_frame: world
  ee_frame: robot2_tool0
  robot_link_command_frame: robot2_tool0

  ## Stopping behaviour
  incoming_command_timeout: 0.1
  num_outgoing_halt_msgs_to_publish: 4

  ## Singularity handling
  lower_singularity_threshold: 100.0
  hard_stop_singularity_threshold: 200.0

  joint_limit_margins: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

  ## Topic names
  cartesian_command_in_topic: ~/delta_twist_cmds
  joint_command_in_topic: ~/delta_joint_cmds
  joint_topic: /joint_states
  status_topic: ~/status
  command_out_topic: /robot2_scaled_joint_trajectory_controller/joint_trajectory

  ## Collision checking
  check_collisions: true
  collision_check_rate: 10.0
  collision_check_type: threshold_distance
  self_collision_proximity_threshold: 0.01
  scene_collision_proximity_threshold: 0.02
