planning_plugins:
  - pilz_industrial_motion_planner/CommandPlanner
default_planner_config: PTP
# Tolerance for start state bounds checking (in radians)
# Prevents "Start State out of Bounds" errors due to float precision
start_state_max_bounds_error: 0.2
request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
response_adapters:
  - default_planning_response_adapters/ValidateSolution
  - default_planning_response_adapters/DisplayMotionPath
capabilities: >-
    pilz_industrial_motion_planner/MoveGroupSequenceAction
    pilz_industrial_motion_planner/MoveGroupSequenceService