kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.15196600814443764
    roll: -0
    pitch: 0
    yaw: -6.2494517823425738e-06
  upper_arm:
    x: -5.5041637525849207e-05
    y: 0
    z: 0
    roll: 1.57035844070046
    pitch: 0
    yaw: -8.3932250998675087e-05
  forearm:
    x: -0.24352641127293065
    y: 0
    z: 0
    roll: 3.1356846987728195
    pitch: -3.1413710112672439
    yaw: 3.1415538408006864
  wrist_1:
    x: -0.21329782692397758
    y: 0.0010510454955557599
    z: 0.11227582389361061
    roll: 3.1322316463984814
    pitch: 3.1409153389980666
    yaw: 3.1415432093193489
  wrist_2:
    x: 4.7791792616600192e-05
    y: -0.085168669188541588
    z: -4.4878659778613337e-07
    roll: 1.5708015961809521
    pitch: 0
    yaw: 8.6814946839921476e-05
  wrist_3:
    x: -0.00016810886884530905
    y: 0.082361911656361114
    z: 6.0095027459152809e-06
    roll: 1.5708692913802782
    pitch: 3.1415926535897931
    yaw: -3.1415437632831136
  hash: calib_2296481876046075298