# UR3 joint limits for URDF (expanded limits)
joint_limits:
  shoulder_pan_joint:
    has_position_limits: true
    min_position: -6.28319
    max_position: 6.28319
    has_velocity_limits: true
    max_velocity: 3.14159
    has_effort_limits: true
    max_effort: 56.0
  shoulder_lift_joint:
    has_position_limits: true
    min_position: -6.28319
    max_position: 6.28319
    has_velocity_limits: true
    max_velocity: 3.14159
    has_effort_limits: true
    max_effort: 56.0
  elbow_joint:
    has_position_limits: true
    min_position: -3.14159
    max_position: 3.14159
    has_velocity_limits: true
    max_velocity: 3.14159
    has_effort_limits: true
    max_effort: 28.0
  wrist_1_joint:
    has_position_limits: true
    min_position: -6.28319
    max_position: 6.28319
    has_velocity_limits: true
    max_velocity: 6.28319
    has_effort_limits: true
    max_effort: 12.0
  wrist_2_joint:
    has_position_limits: true
    min_position: -6.28319
    max_position: 6.28319
    has_velocity_limits: true
    max_velocity: 6.28319
    has_effort_limits: true
    max_effort: 12.0
  wrist_3_joint:
    has_position_limits: true
    min_position: -6.28319  # -360 deg
    max_position: 6.28319   # +360 deg
    has_velocity_limits: true
    max_velocity: 6.28319
    has_effort_limits: true
    max_effort: 12.0
